export const GET_PEOPLE_INFO_LIST_REQUEST: "GET_PEOPLE_INFO_LIST_REQUEST" =
  "GET_PEOPLE_INFO_LIST_REQUEST";

export const GET_PEOPLE_INFO_LIST_SUCCESS: "GET_PEOPLE_INFO_LIST_SUCCESS" =
  "GET_PEOPLE_INFO_LIST_SUCCESS";

export const GET_PEOPLE_INFO_LIST_FAILED: "GET_PEOPLE_INFO_LIST_FAILED" =
  "GET_PEOPLE_INFO_LIST_FAILED";
